config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords,], controllers: {
    registlations: 'public/registlations',
     sessions: 'public/sessions'
   }
  # devise_for :customers, skip: :all
  # devise_scope :customer do
  #   get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customers_session'
  #   post 'customers/sign_in' => 'customers/sessions#create', as: 'customers_session'
  #   delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customers_session'
  #   get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customers_registration'
  #   post 'customers' => 'customers/registrations#create', as: 'customers_registration'
  #   get 'customers/password/new' => 'customers/passwords#new', as: 'new_customers_password'
  # end

  devise_for :admins,skip: [:registlations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

scope module: :public do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  resources :items, only:[:index,:show]

  patch 'customers/quit' => 'customers#quit'
  resources :customers, only:[:edit,:update]
  get 'customers/my_page' => 'customers#show'
  get 'customers/unsubscribe' => 'customers#unsubscribe'


   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only:[:index,:update,:destroy,:create]
  #似たようなアクションがある時は順番に注意（destroyよりdestroy_allを優先）


  resources :orders, only:[:index,:create,:show,:new]
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'


  resources :addresses, except:[:show,:new]



end

namespace :admin do
  root to: 'homes#top'

  resources :items, except: [:destroy]

  resources :genres, only: [:index, :create, :edit, :update]


  resources :customers, only: [:index, :show, :edit, :update]

  resources :orders, only: [:show, :update]

  resources :order_details, only: [:update]




end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses
         has_many :orders
         has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

 def index
  @customers = Customer.all
 end

 def show
  @customer = Customer.find(params[:id])
 end

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  @customer.update
  redirect_to
 end

 private
 def customer_params
   params.require(:customer).permit(:email,:last_name,:first_name,:last_name_kana,:first_name_kana,:address,:telephone_number,:postal_code)
 end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  genre = Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
  
end

private
def genre_params
  params.require(:genre).permit(:name)
  
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 def top
   @orders = Order.all
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
 @item = Item.new

  @array = Genre.all.map do |genre|
    [genre.name, genre.id]
  end
end

def index
  @items = Item.all
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)

end

def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])

    @array = Genre.all.map do |genre|
    [genre.name, genre.id]
  end

end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path
end

private
def item_params
  params.require(:item).permit(:name,:image,:introduction,:price,:genre_id)
end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
  @order = Order.find(params[:id])
  @customer = @order.customer
  @order_details = @order.order_details
end

def update
 @order = Order.find(params[:id])
 @order.updete(order_params)
 redirect_to admin_order_path(order.id)
end


private
 def order_params
   params.require(:order).permit(:customer_id,:postal_code,:address,:name,:shipping_cost,:total_payment,:payment_method)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number])
  end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <div class="container">
    <div class="row">
     <div class="col-4 text-center bg-light">
      <h3><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h3>
      </div>
    </div>

   <%= form_with model:[:admin,@customer], local:true do |f| %>
     <div class="row">
       <div class="col">会員ID</div>
       <div class="col"><%= @customer.id %></div>
     </div>
     <div class="row">
       <div class="col">氏名</div>
       <div class="col"><%= f.text_field :last_name %></div>
       <div class="col"><%= f.text_field :first_name %></div>
     </div>
     <div class="row">
       <div class="col">フリガナ</div>
       <div class="col"><%= f.text_field :last_name_kana %></div>
       <div class="col"><%= f.text_field :first_name_kana %></div>
     </div>
      <div class="row">
       <div class="col">郵便番号</div>
       <div class="col"><%= f.text_field :postal_code %></div>
     </div>
      <div class="row">
       <div class="col">住所</div>
       <div class="col"><%= f.text_field :address %></div>
     </div>
      <div class="row">
       <div class="col">電話番号</div>
       <div class="col"><%= f.text_field :teelphone_number %></div>
     </div>
      <div class="row">
       <div class="col">メールアドレス</div>
       <div class="col"><%= f.text_field :email %></div>
     </div>
     <div class="row">
        <button class="btn btn-success">変更を保存</button>
    </div>
   <% end %>
  </div>
</main>

app/views/admin/customers/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light">
      <h4>会員一覧</h4>
      </div>
    </div>
    <div class="row">

        <table class="table">
          <thead>
            <tr>
              <th>会員ID</th>
              <th>氏名</th>
              <th>メールアドレス</th>
              <th colspan="3"></th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
             <tr>
               <td>
                 <%= customer.id %>
               </td>
              <td>
                <%= link_to  admin_customer_path(customer.id) do %>
                <%= customer.last_name %><%= customer.first_name %>
                <% end %>
              </td>
              <td>
                <%= customer.email %>
              </td>
              <td>

              </td>
              <td>
                <% if customer.is_active == true %>有効
                <% else %>退会
                <% end %>
              </td>

            </tr>
            <% end %>
          </tbody>

        </table>


    </div>



  </div>
</main>

app/views/admin/customers/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light">
      <h3><%= @customer.last_name %><%= @customer.first_name %> 会員詳細</h3>
      </div>
    </div>
    <div class="col-8">
      <table>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.first_name %><%= @customer.last_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.first_name_kana %><%= @customer.last_name_kana %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
      </table>
    </div>
    <div class="row">
      <div class="col-6">
        <%= link_to edit_admin_customer_path do %>
        <button class="btn btn-success">編集する</button>
        <% end %>
      </div>
    </div>
 


  </div>
</main>

app/views/customers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/customers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>



<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>