config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords,], controllers: {
    registlations: 'public/registlations',
     sessions: 'public/sessions'
   }
  # devise_for :customers, skip: :all
  # devise_scope :customer do
  #   get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customers_session'
  #   post 'customers/sign_in' => 'customers/sessions#create', as: 'customers_session'
  #   delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customers_session'
  #   get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customers_registration'
  #   post 'customers' => 'customers/registrations#create', as: 'customers_registration'
  #   get 'customers/password/new' => 'customers/passwords#new', as: 'new_customers_password'
  # end

  devise_for :admins,skip: [:registlations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

scope module: :public do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  resources :items, only:[:index,:show]

  patch 'customers/quit' => 'customers#quit'
  resources :customers, only:[:edit,:update]
  get 'customers/my_page' => 'customers#show'
  get 'customers/unsubscribe' => 'customers#unsubscribe'


   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only:[:index,:update,:destroy,:create]
  #似たようなアクションがある時は順番に注意（destroyよりdestroy_allを優先）


  resources :orders, only:[:index,:create,:show,:new]
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'


  resources :addresses, except:[:show,:new]



end

namespace :admin do
  root to: 'homes#top'

  resources :items, except: [:destroy]

  resources :genres, only: [:index, :create, :edit, :update]


  resources :customers, only: [:index, :show, :edit, :update]

  resources :orders, only: [:show, :update]

  resources :order_details, only: [:update]




end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses
         has_many :orders
         has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  genre = Genre.new(genre_params)
  genre.save
  redirect_to admin_genres_path
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
  
end

private
def genre_params
  params.require(:genre).permit(:name)
  
end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 def top
   @orders = Order.all
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
 @item = Item.new

  @array = Genre.all.map do |genre|
    [genre.name, genre.id]
  end
end

def index
  @items = Item.all
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)

end

def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])

    @array = Genre.all.map do |genre|
    [genre.name, genre.id]
  end

end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path
end

private
def item_params
  params.require(:item).permit(:name,:image,:introduction,:price,:genre_id)
end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

def show
  @order = Order.find(params[:id])
  @customer = @order.customer
  @order_details = @order.order_details
end

def update
 @order = Order.find(params[:id])
 @order.updete(order_params)
 redirect_to admin_order_path(order.id)
end


private
 def order_params
   params.require(:order).permit(:customer_id,:postal_code,:address,:name,:shipping_cost,:total_payment,:payment_method)
 end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number])
  end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light">
      <h4>ジャンル編集</h4>
      </div>
    </div>
    <div class="row">
      <%= form_with model: @genre, url: admin_genre_path(@genre), local:true do |f| %>
        <div class="form_group">
          <label for="genre_name">ジャンル名</label>
          <%= f.text_field :name %>
          <%= f.submit '変更を保存', class:"btn btn-success" %>
        </div>
        <% end %>

          </tbody>

        </table>


    </div>



  </div>
</main>

app/views/admin/genres/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light">
      <h4>ジャンル一覧・追加</h4>
      </div>
    </div>
    <div class="row">
      <%= form_with model:@genre,url:admin_genres_path, local:true do |f| %>
        <div class="form_group">
          <label for="genre_name">ジャンル名</label>
          <%= f.text_field :name %>
          <%= f.submit '新規登録', class: "btn btn-success" %>
        </div>
        <% end %>
        </div>

      <div class="row">
        <div class="col-5"></div>
        <table class="table">
          <thead>
            <tr>
              <th>ジャンル</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
             <tr>
              <td>
                <%= genre.name %>
              </td>
              <td>
              <%= link_to edit_admin_genre_path(genre.id) do %>
               <button class="btn btn-success">編集する</button>
              <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
       
        </div>


 



  </div>
</main>

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <div class="row">
    <div class="col-4 text-center bg-light">
      <h3>商品編集</h3>
      </div>
     <div class="col-8"></div>
    </div>

    <%= form_with model:[:admin,@item], local:true do |f| %>
         <div class="row">
          <div class="col-4 text-center">
           <label for="item_image">商品画像</label>
          </div>
          <div class="col-6 ">
           <div class="form_group">
           <%= f.file_field :image_id %>
           </div>
          </div>
         </div>

         <div class="row">
          <div class="col-4 text-center">
           <label for="item_name">商品名</label>
           </div>
          <div class="col-6"><%= f.text_field :name %></div>
         </div>

         <div class="row">
           <div class="col-4 text-center">
            <label for="item_introduction">商品説明</label>
           </div>
           <div class="col">
            <%= f.text_field :introduction %>
           </div>
           </div>

         <div class="row">
          <div class="col-4 text-center">
           <label for="genre">ジャンル</label>
          </div>
          <div class="col-6">
          <%= f.select :genre_id, @array, { selected: 1 } %>
          </div>
         </div>

         <div class="row">
          <div class="col-4 text-center">
           <label for="item_price">税抜価格</label>
          </div>
          <div class="col-6">
           <%= f.text_field :price %>円
          </div>
         </div>

         <div class="row">
            <div class="col text-center">
            <%= f.submit '変更を保存', class:"btn btn-success" %>
            </div>
         </div>

    <% end %>
  </div>
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light ">
      <h3>商品一覧</h3>
      </div>
      <div class="col text-right ">
        <%= link_to  new_admin_item_path do %>
        <button type="button" class="btn btn-light rounded-circle p-0" style="width:2rem;height:2rem;">＋</button>
        <% end %>
      </div>
    </div>
    <div class="row">
        <table class="table">
          <thead>
            <tr>
              <th>商品ID</th>
              <th>商品名</th>
              <th>税抜価格</th>
              <th>ジャンル</th>
              <th colspan="3"></th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
             <tr>
               <td>
                 <%= item.id %>
               </td>
              <td>
                <%= link_to item.name, admin_item_path(item.id), class: "text-dark border-bottom " %>
              </td>
              <td>
                <%= item.price %>
              </td>
              <td>
                <%= item.genre.name %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <div class="row">
      <h3>商品新規登録</h3>
    </div>
    <%= form_with model:@item, url:admin_items_path, local:true do |f| %>
        <div class="form_group">
          <label for="item_image">商品画像</label>
          <%= f.attachment_field :image %>
        </div>
         <div class="form_group">
          <label for="item_name">商品名</label>
          <%= f.text_field :name, class: "form-control" %>
         </div>
          <div class="form_group">
          <label for="item_introduction">商品説明</label>
          <%= f.text_field :introduction, class: "form-control"%>
         </div>
          <div class="form_group">
            <label for="genre">ジャンル</label>
           <%= f.select :genre_id, @array, { selected: 1 } ,class: "form-control"%>
           <!--include_blank: true,-->

          <!--array = []-->
          <!--Genre.all.each do |genre|-->
          <!--  array.push([genre.name, genre.id])-->
          <!--end-->

          <!--array = Genre.all.map do |genre|-->
          <!--  [genre.name, genre.id]-->
          <!--end-->
         </div>
         <div class="form_group">
          <label for="item_price">税抜価格</label>
          <%= f.text_field :price, class: "form-control" %>円
         </div>
         <div class="row">
           <%= f.submit '新規登録', class:"btn btn-success" %>
         </div>

      <% end %>
  </div>
</main>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light">
      <h3>商品詳細</h3>
      </div>
    </div>
    <div class="row">
    <div class="col-4">
      <div>
        <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: 'no_image.jpg', size:"200x200" %>
      </div>
    </div>
    <div class="col-8">
      <table>
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格</td>
          <td><%= @item.price %></td>
        </tr>
      </table>
    </div>
    </div>
    <div class="row">
      <div class="col-9 text-center">
      <%= link_to edit_admin_item_path do %>
       <button class="btn btn-success">編集する</button>
       <% end %>
       </div>
    </div>



  </div>
</main>

app/views/admin/orders/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-4 text-center bg-light">
      <h3>注文詳細</h3>
      </div>
    </div>
    <div class="row">
      <div class="col">購入者</div>
      <div class="col"><%= link_to @customer.last_name + @customer.first_name, admin_customer_path(@customer)%></div>
    </div>
    <div class="row">
      <div class="col">注文日</div>
      <div class="col"><%= @order.created_at.strftime('%Y/%m/%d') %></div>
    </div>
    <div class="row">
      <div class="col">配送先</div>
      <div class="col">〒<%= @order.postal_code %><%= @order.address %></div>
    </div>
    <div class="row">
      <div class="col"></div>
      <div class="col"><%= @order.name %></div>
    </div>
    <div class="row">
      <div class="col">支払方法</div>
      <div class="col"><%= @order.payment_method_i18n %></div>
    </div>


    <div class="row">
      <div class="col">
        <table class="table">
          <thead>
            <tr>
              <th>商品名</th>
              <th>単価（税込）</th>
              <th>数量</th>
              <th>小計</th>
              <th colspan="3"></th>
              <th>ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @sum = 0 %>
            <% @order_details.each do |order| %>
             <tr>
               <td>
                <%= order.item.name %>
               </td>
              <td>
                <%= order.item.price %>
              </td>
              <td>
                <%= order.amount %>
              </td>
              <td>
                <%= (order.item.price * 1.1).floor * order.amount %>
                <% @sum += (order.item.price * 1.1).floor * order.amount %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        </div>
       <div class="row">
         <div class="col">
             <table  class="table">
            <tr>
              <th>商品合計</th>
              <td><%= @sum %></td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= 800 %></td>
            </tr>
            <tr>
              <th>請求金額</th>
              <td><%= (@sum + 800) %></td>
            </tr>
          </table>
         </div>

       </div>

        </div>
    </div>
  </div>
</main>