config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords,], controllers: {
    registlations: 'public/registlations',
     sessions: 'public/sessions'
   }
  # devise_for :customers, skip: :all
  # devise_scope :customer do
  #   get 'customers/sign_in' => 'customers/sessions#new', as: 'new_customers_session'
  #   post 'customers/sign_in' => 'customers/sessions#create', as: 'customers_session'
  #   delete 'customers/sign_out' => 'customers/sessions#destroy', as: 'destroy_customers_session'
  #   get 'customers/sign_up' => 'customers/registrations#new', as: 'new_customers_registration'
  #   post 'customers' => 'customers/registrations#create', as: 'customers_registration'
  #   get 'customers/password/new' => 'customers/passwords#new', as: 'new_customers_password'
  # end

  devise_for :admins,skip: [:registlations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

scope module: :public do
  root to: 'homes#top'
  get 'homes/about' => 'homes#about'

  resources :items, only:[:index,:show]

  patch 'customers/quit' => 'customers#quit'
  resources :customers, only:[:edit,:update]
  get 'customers/my_page' => 'customers#show'
  get 'customers/unsubscribe' => 'customers#unsubscribe'


   delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only:[:index,:update,:destroy,:create]
  #似たようなアクションがある時は順番に注意（destroyよりdestroy_allを優先）


  resources :orders, only:[:index,:create,:show,:new]
  post 'orders/confirm' => 'orders#confirm'
  get 'orders/thanks' => 'orders#thanks'


  resources :addresses, except:[:show,:new]



end

namespace :admin do
  root to: 'homes#top'

  resources :items, except: [:destroy]

  resources :genres, only: [:index, :create, :edit, :update]


  resources :customers, only: [:index, :show, :edit, :update]

  resources :orders, only: [:show, :update]

  resources :order_details, only: [:update]




end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :addresses
         has_many :orders
         has_many :cart_items
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image

  belongs_to :genre
  has_many :cart_items
  has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 def top
   @orders = Order.all
 end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

def new
 @item = Item.new

  @array = Genre.all.map do |genre|
    [genre.name, genre.id]
  end
end

def index
  @items = Item.all
end

def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)

end

def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])

    @array = Genre.all.map do |genre|
    [genre.name, genre.id]
  end

end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path
end

private
def item_params
  params.require(:item).permit(:name,:image,:introduction,:price,:genre_id)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:first_name,:last_name,:first_name_kana,:last_name_kana,:postal_code,:address,:telephone_number])
  end

 def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :customer
        root_path
    elsif resource_or_scope == :admin
        new_admin_session_path
    else
        root_path
    end
 end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganocakeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   <script src="https://kit.fontawesome.com/648215ea55.js" crossorigin="anonymous"></script>
  </head>

  <body>
   <header class="border-bottom" >
      <nav class="navbar navbar-expand-lg navbar-white bg-white">
        <div class="container">
          <a class="navbar-brand" href="/"><span class="text-dark border border-dark">LOGO</span></a>

        <ul class="nav navbar-nav ml-auto">
         <% if admin_signed_in? %>
           <li>
            <%= link_to "商品一覧", admin_items_path ,class: "btn btn-outline-secondary" %>
          </li>
           <li>
            <%= link_to "会員一覧", admin_customers_path ,class: "btn btn-outline-secondary" %>
          </li>
           <li>
            <%= link_to"注文履歴一覧", admin_root_path ,class: "btn btn-outline-secondary" %>
          </li>
           <li>
            <%= link_to"ジャンル一覧", admin_genres_path ,class: "btn btn-outline-secondary" %>
          </li>
           <li>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete ,class: "btn btn-outline-secondary" %>
          </li>
          <% elsif customer_signed_in? %>
          <li>
            <%= link_to"マイページ", customers_my_page_path ,class: "btn btn-outline-secondary"  %>
          </li>
           <li>
            <%= link_to"商品一覧", items_path ,class: "btn btn-outline-secondary"  %>
          </li>
           <li>
            <%= link_to "カート", cart_items_path ,class: "btn btn-outline-secondary" %>
          </li>
          <li>
           <%= link_to "ログアウト", destroy_customer_session_path, method: :delete ,class: "btn btn-outline-secondary" %>
          </li>
         <% else %>
           <li>
            <%= link_to"About", homes_about_path ,class: "btn btn-outline-secondary"  %>
          </li>
           <li>
            <%= link_to"商品一覧", items_path ,class: "btn btn-outline-secondary"  %>
          </li>
           <li>
            <%= link_to "新規登録", new_customer_registration_path ,class: "btn btn-outline-secondary" %>
          </li>
           <li>
            <%= link_to "ログイン", new_customer_session_path ,class: "btn btn-outline-secondary" %>
          </li>
         <% end %>


        </ul>
      </div>
      </div>

      </nav>
    </header>
    <%= yield %>
    <footer class="border-top"></footer>
  </body>
</html>